name: Update theme

# Controls when the workflow will run
on:
  schedule:
    # Update theme automatically everyday at 00:00 UTC
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  Update-FixIt-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update theme components
        run: |
          git submodule update --remote --merge

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Generate hugo-fixit component list
        id: action-component-list
        uses: hugo-fixit/action-component-list@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          comment_tag_name: HUGO_FIXIT_COMPONENTS
          readme_path: 'README.md'
          exclude_repos: 'fixit-bundle'
          template: "- [{$repo.name}]({$repo.html_url})\\\n {$repo.description}"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'chore(deps): update theme and components version'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
